# Generated by Django 5.2.8 on 2026-01-14 07:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('Number', models.AutoField(primary_key=True, serialize=False, verbose_name='No.')),
                ('Name', models.CharField(max_length=30, verbose_name='Medicine Name')),
                ('Code', models.CharField(max_length=50, unique=True)),
                ('Category', models.CharField(choices=[('Tablets', 'Tablets'), ('Syrup', 'Syrup'), ('Injections', 'Injections'), ('Capsules', 'Capsules'), ('Effervescent', 'Effervescent Tablets'), ('Suppositories', 'Suppositories'), ('Cream', 'Cream'), ('Ointment', 'Ointment')], max_length=25, null=True)),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('MinStock', models.PositiveIntegerField(default=0, verbose_name='Minimum Stock Level')),
                ('Price', models.PositiveIntegerField(default=0, verbose_name='Unit Price')),
                ('Expiry', models.DateField(verbose_name='Expiry Date')),
            ],
            options={
                'verbose_name_plural': 'Medicines',
                'db_table': 'Medicines',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Supplier Name')),
                ('Contact', models.CharField(max_length=20, verbose_name='Contact Person')),
                ('Phone', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('City', models.CharField(max_length=15)),
                ('Address', models.TextField(max_length=200, null=True)),
                ('Contract', models.DateField(auto_now_add=True, verbose_name='Contract Date')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'db_table': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('medicine', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PharmacySystem.medicines', verbose_name='Medicine')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Scientific Description')),
                ('side_effects', models.TextField(blank=True, null=True, verbose_name='Side Effects')),
                ('Box_Shape', models.FileField(blank=True, null=True, upload_to='document/', verbose_name='Medicine Image')),
            ],
            options={
                'verbose_name_plural': 'MedicineDetails',
                'db_table': 'MedicineDetails',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('Number', models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('Sold', models.PositiveIntegerField(verbose_name='Quantity Sold')),
                ('Unit_Price', models.PositiveIntegerField(editable=False, verbose_name='Unit Price')),
                ('Total', models.PositiveIntegerField(editable=False)),
                ('Date', models.DateField(auto_now_add=True, verbose_name='Sale Date')),
                ('Customer', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PharmacySystem.medicines', verbose_name='Medicine Name')),
            ],
            options={
                'verbose_name_plural': 'Sales',
                'db_table': 'Sales',
            },
        ),
        migrations.AddField(
            model_name='medicines',
            name='suppliers',
            field=models.ManyToManyField(related_name='medicines', to='PharmacySystem.suppliers', verbose_name='Suppliers'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
